### ISSUE TITLE
Problem Youtube API

### ISSUE THREAD

**Issue by turpez** [freQuensy23-coder/TickTok-content-farm#2]
I don't know where to put the youtube api key

Traceback (most recent call last):
  File ".\main.py", line 65, in <module>
    api = Api(api_key=youtube_api_key)
NameError: name 'youtube_api_key' is not defined

**Comment by benkiller47** [comment]
Can you give me the config file, it seems to be missing from the github folder?

Thank you very much

**Comment by turpez** [comment]
How's the config file ?

**Comment by turpez** [comment]
What do you need ?

**Comment by zbeucler2018** [comment]
In your main.py file at line 65, 
```

api = Api(api_key="your api key here")

```

**Comment by turpez** [comment]
if __name__ == '__main__':
    api = Api(api_key=youtube_api_key)
    log.debug("API inited")
    do = True

**Comment by turpez** [comment]
line 64 to 67

**Comment by zbeucler2018** [comment]
> if __name__ == '__main__':
> 
>     api = Api(api_key=youtube_api_key)
> 
>     log.debug("API inited")
> 
>     do = True

Replace `YouTube_api_key` with your YouTube API key on line 65 and I believe it should work. Do you know how to get a YouTube api key?

**Comment by turpez** [comment]
I put them and its me but name error is not defined

**Comment by turpez** [comment]
must go to the google cloud and have the youtube key is that?

**Comment by zbeucler2018** [comment]
> I put them and its me but name error is not defined

You replaced `youtube_api_key` with your YouTube api key and you are still getting the same name error? It is still undefined?

**Comment by turpez** [comment]
yes

**Comment by turpez** [comment]
he tells me that the key is not defined

**Comment by zbeucler2018** [comment]
> must go to the google cloud and have the youtube key is that?
> 
> 

Yes I believe you get the YouTube API keys from Google. This site should help https://developers.google.com/youtube/v3/getting-started

**Comment by turpez** [comment]
I don't know why my key is not defined

**Comment by turpez** [comment]
Do you have a solution?


Do you have the same problem?

**Comment by benkiller47** [comment]
> How's the config file ?

Is isn't there supposed to be a config file inside of the folder? in github you can only download 4 files , souldn't it have a config file also? 

It gives me this error : 
python3 main.py
Traceback (most recent call last):
  File "/home/mrdev/tiktok/TikTok-content-farm/main.py", line 4, in <module>
    from config import *
ModuleNotFoundError: No module named 'config'

Thank  you

**Comment by turpez** [comment]
![testP](https://user-images.githubusercontent.com/29740508/119995448-de143800-bfcd-11eb-927f-24fceebefd8d.PNG)

**Comment by turpez** [comment]
In my file there is that his

**Comment by thanhtuvietnam** [comment]
can you give me a youtube api key, i don't have it but i really want to try your sripts.
